### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by wei-hub** [IanYeung/RealVSR#10]
How can I solve this problem when I run it?

(realvsr) lzw@computer3:~/code/RealVSR/RealVSR-main/codes$ python test_RealVSR_wi_GT.py
22-04-06 17:05:11.072 - INFO: Data: RealVSR - /home/lzw/code/data/ycbcr/LQ_YCbCr_test
22-04-06 17:05:11.073 - INFO: Padding mode: replicate
22-04-06 17:05:11.073 - INFO: Model path: /home/lzw/code/data/ycbcr/RealVSR-Models/001_EDVR_NoUp_woTSA_scratch_lr1e-4_150k_RealVSR_3frame_WiCutBlur_YCbCr_LapPyr+GW.pth
22-04-06 17:05:11.073 - INFO: Save images: True
Traceback (most recent call last):
  File "test_RealVSR_wi_GT.py", line 220, in <module>
    main()
  File "test_RealVSR_wi_GT.py", line 98, in main
    imgs = data_util.read_img_seq(subfolder, color=color)
  File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 116, in read_img_seq
    img_l = [read_img(None, v) for v in img_path_l]
  File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 116, in <listcomp>
    img_l = [read_img(None, v) for v in img_path_l]
  File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 95, in read_img
    img = img.astype(np.float32) / 255.
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by IanYeung** [comment]
> How can I solve this problem when I run it?
> 
> (realvsr) lzw@computer3:~/code/RealVSR/RealVSR-main/codes$ python test_RealVSR_wi_GT.py 22-04-06 17:05:11.072 - INFO: Data: RealVSR - /home/lzw/code/data/ycbcr/LQ_YCbCr_test 22-04-06 17:05:11.073 - INFO: Padding mode: replicate 22-04-06 17:05:11.073 - INFO: Model path: /home/lzw/code/data/ycbcr/RealVSR-Models/001_EDVR_NoUp_woTSA_scratch_lr1e-4_150k_RealVSR_3frame_WiCutBlur_YCbCr_LapPyr+GW.pth 22-04-06 17:05:11.073 - INFO: Save images: True Traceback (most recent call last): File "test_RealVSR_wi_GT.py", line 220, in main() File "test_RealVSR_wi_GT.py", line 98, in main imgs = data_util.read_img_seq(subfolder, color=color) File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 116, in read_img_seq img_l = [read_img(None, v) for v in img_path_l] File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 116, in img_l = [read_img(None, v) for v in img_path_l] File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 95, in read_img img = img.astype(np.float32) / 255. AttributeError: 'NoneType' object has no attribute 'astype'

This means the loading function does not load any image. Please check the loading path.

**Comment by wei-hub** [comment]
Thanks for your reply，Excuse me what the&nbsp;loading path refers to ？Do you mean the one in my screenshot?







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xi ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 晚上8:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IanYeung/RealVSR] Problem running (Issue #10)





  
How can I solve this problem when I run it?
 
(realvsr) ***@***.***:~/code/RealVSR/RealVSR-main/codes$ python test_RealVSR_wi_GT.py 22-04-06 17:05:11.072 - INFO: Data: RealVSR - /home/lzw/code/data/ycbcr/LQ_YCbCr_test 22-04-06 17:05:11.073 - INFO: Padding mode: replicate 22-04-06 17:05:11.073 - INFO: Model path: /home/lzw/code/data/ycbcr/RealVSR-Models/001_EDVR_NoUp_woTSA_scratch_lr1e-4_150k_RealVSR_3frame_WiCutBlur_YCbCr_LapPyr+GW.pth 22-04-06 17:05:11.073 - INFO: Save images: True Traceback (most recent call last): File "test_RealVSR_wi_GT.py", line 220, in main() File "test_RealVSR_wi_GT.py", line 98, in main imgs = data_util.read_img_seq(subfolder, color=color) File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 116, in read_img_seq img_l = [read_img(None, v) for v in img_path_l] File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 116, in img_l = [read_img(None, v) for v in img_path_l] File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 95, in read_img img = img.astype(np.float32) / 255. AttributeError: 'NoneType' object has no attribute 'astype'
  
This means the loading function does not load any image. Please check the loading path.

**Comment by IanYeung** [comment]
> Thanks for your reply，Excuse me what the&nbsp;loading path refers to ？Do you mean the one in my screenshot?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xi ***@***.***&gt;; 发送时间: 2022年4月6日(星期三) 晚上8:34 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [IanYeung/RealVSR] Problem running (Issue #10) How can I solve this problem when I run it? (realvsr) ***@***.***:~/code/RealVSR/RealVSR-main/codes$ python test_RealVSR_wi_GT.py 22-04-06 17:05:11.072 - INFO: Data: RealVSR - /home/lzw/code/data/ycbcr/LQ_YCbCr_test 22-04-06 17:05:11.073 - INFO: Padding mode: replicate 22-04-06 17:05:11.073 - INFO: Model path: /home/lzw/code/data/ycbcr/RealVSR-Models/001_EDVR_NoUp_woTSA_scratch_lr1e-4_150k_RealVSR_3frame_WiCutBlur_YCbCr_LapPyr+GW.pth 22-04-06 17:05:11.073 - INFO: Save images: True Traceback (most recent call last): File "test_RealVSR_wi_GT.py", line 220, in main() File "test_RealVSR_wi_GT.py", line 98, in main imgs = data_util.read_img_seq(subfolder, color=color) File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 116, in read_img_seq img_l = [read_img(None, v) for v in img_path_l] File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 116, in img_l = [read_img(None, v) for v in img_path_l] File "/home/lzw/code/RealVSR/RealVSR-main/codes/data/util.py", line 95, in read_img img = img.astype(np.float32) / 255. AttributeError: 'NoneType' object has no attribute 'astype' This means the loading function does not load any image. Please check the loading path. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

22-04-06 17:05:11.072 - INFO: Data: RealVSR - /home/lzw/code/data/ycbcr/LQ_YCbCr_test
